apiVersion: v1
kind: Service
metadata:
  name: {{ include "goldpinger.fullname" . }}
  labels:
    app: goldpinger
    app.kubernetes.io/name: {{ include "goldpinger.name" . }}
    helm.sh/chart: {{ include "goldpinger.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
  selector:
    app.kubernetes.io/name: {{ include "goldpinger.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
