kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "overlay-check.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "overlay-check.name" . }}
    helm.sh/chart: {{ include "overlay-check.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps", "extensions"] # "" indicates the core API group
  resources: ["daemonsets"]
  verbs: ["get", "watch", "list"]
